name: biobb_wf_flexserv
channels:
  - conda-forge
  - bioconda
dependencies:
  - biobb_flexserv==5.2.0
  - biobb_io==5.2.0
  - biobb_structure_utils==5.2.0
  - biobb_analysis==5.2.0
  - plotly
  - jupyterlab=3.6
  - nodejs=16
  - ipywidgets=7
  - nglview
  - simpletraj
